<a href="https://colab.research.google.com/github/vaibhavlokunde/AI-ML/blob/main/prac3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Reproducibility(trying to take random out of random)
this is how neural networks work:

start with random numbers -> tensor op ->update random numbers to try and make them of the data -> again -> again

To reduce the randomness in neural networks and Pytorch comes the concept of random seed.



In [1]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
tensor_A=torch.rand(3,4)
tensor_B=torch.rand(3,4) # This gives random values all the time
tensor_A,tensor_B


(tensor([[0.8890, 0.1847, 0.9122, 0.2454],
         [0.0009, 0.8317, 0.3268, 0.0358],
         [0.1390, 0.7667, 0.0505, 0.0261]]),
 tensor([[0.8832, 0.0485, 0.2321, 0.4841],
         [0.7579, 0.6761, 0.7253, 0.9701],
         [0.0808, 0.2218, 0.3803, 0.5342]]))

RANDOM_SEED = 42 is assigning the value 42 to the variable RANDOM_SEED. This value is then used in torch.manual_seed(RANDOM_SEED) to set the seed for PyTorch's random number generator.

By setting the seed to 42, all subsequent random operations (like generating random tensors with torch.rand) will produce the same results every time the code is run, ensuring reproducibility. The line tensor_A = torch.rand(3, 4) creates a 3x4 tensor of random values based on this fixed seed.

In [6]:
#Thus to reduce the randomness and making sure we get the same value we use manual seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
tensor_A=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
tensor_B=torch.rand(3,4)
print(tensor_A)
print(tensor_B)
print(tensor_A==tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [4]:
#Setup Device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)
#Move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')