<a href="https://colab.research.google.com/github/vaibhavlokunde/AI-ML/blob/main/prac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


Introduction to Tensors

Creating Tensors

In [ ]:
#scalar type
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back into python int
scalar.item()

7

**VECTOR**

In [ ]:
#vector type
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

**MATRIX**

In [ ]:
#MATRIX
matrix=torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[0]

tensor([1, 2])

**TENSOR**

In [ ]:
#TENSOR
tensor=torch.tensor([[[1,2,3],[3,4,5],[5,3,1]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 3, 1]]])

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor.ndim

3

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 3, 1]])

RANDOM **TENSORS**

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.2091, 0.7966, 0.5061, 0.7066],
        [0.6755, 0.0071, 0.6497, 0.5918],
        [0.8326, 0.8748, 0.1632, 0.6762]])

In [ ]:
random_tensor.ndim

2

**CREATING A RANDOM TENSOR WITH SIMILAR SHAPE TO AN IMAGE TENSOR**

In [ ]:
random_image=torch.rand(size=(224,224,3)) #height,width,color channels
random_image.shape,
random_image.ndim

3

**CREATING A TENSOR WITH ALL ZEROS**

In [ ]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

**CREATING A TENSOR WITH ALL ONES**

In [ ]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**CREATING A RANGE OF TENSORS**

In [ ]:
##there are 2 types torch.range(1,10) and torch.arange(1,10)
##..but torch.range will be removed
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten=torch.arange(1,20,2)
one_to_ten

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
##Creating tensors like
ten_zeros=torch.zeros_like(one_to_ten)
#OR torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**TENSOR DATATYPES**
float 32"
they are used when we have to change datatypes while training models

In [3]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,#what datatype is the tensor(float32,float16)
                             device=None, #what device is your tensor on
                             requires_grad=False)#whether or not to track gradience
float_32_tensor

tensor([3., 6., 9.])

In [4]:
float_32_tensor.dtype

torch.float32

**FLOAT 16 DTYPE**

In [5]:
float_16_tensor=float_32_tensor.type(torch.float16) # OR .type(torch.half) is the same
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [7]:
float_16_tensor=torch.tensor([3.0,7.0,8.0],
                             dtype=torch.float16,
                             device=None,
                             requires_grad=False
                             )
float_16_tensor

tensor([3., 7., 8.], dtype=torch.float16)

In [8]:
float_16_tensor * float_32_tensor

tensor([ 9., 42., 72.])

**INT dTYPE**

In [10]:
int_32_tensor=torch.tensor([3,6,9],
                           dtype=torch.int32,
                           device=None,
                           requires_grad=False)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [11]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

Following are few errors that might come while training models

1.   Tensors not in right datatype(use tensor.dtype)
2.   Tensors not in right shape(use tensor.shape)
3.   Tensors not on right device(use tensor.device)






**Example of getting info from tensors**

In [12]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.6683, 0.9996, 0.8064, 0.7417],
        [0.9231, 0.5285, 0.9329, 0.5427],
        [0.6008, 0.6156, 0.3900, 0.1785]])

In [13]:
print(some_tensor)
print(f"data type:{some_tensor.dtype}")
print(f"shape type:{some_tensor.shape}")

tensor([[0.6683, 0.9996, 0.8064, 0.7417],
        [0.9231, 0.5285, 0.9329, 0.5427],
        [0.6008, 0.6156, 0.3900, 0.1785]])
data type:torch.float32
shape type:torch.Size([3, 4])


In [14]:
some_tensor.shape

torch.Size([3, 4])

In [15]:
some_tensor.size

<function Tensor.size>

**MANIPULATING TENSORS**

Addition

In [16]:
Tensor=torch.tensor([1,2,3])
Tensor+10

tensor([11, 12, 13])

In [17]:
Tensor-10

tensor([-9, -8, -7])

In [18]:
torch.add(Tensor,10)

tensor([11, 12, 13])

In [19]:
torch.sub(Tensor,10)

tensor([-9, -8, -7])

In [20]:
torch.div(Tensor,10)

tensor([0.1000, 0.2000, 0.3000])

**MATRIX MULTIPLICATION**

*   Two main ways of matrix mul

1.   element-wise
2.   dot prod





In [22]:
#element wise
Tensor * Tensor

tensor([1, 4, 9])

In [23]:
#dot product
torch.matmul(Tensor,Tensor)

tensor(14)

In [3]:
torch.matmul(torch.rand(10,10),torch.rand(10,4))

tensor([[2.0587, 1.5090, 2.4909, 2.1779],
        [2.5106, 2.1467, 3.3058, 2.1948],
        [2.8585, 2.6218, 3.1067, 2.7271],
        [1.9562, 1.4215, 1.7293, 1.5497],
        [2.5455, 2.1822, 3.1528, 2.6095],
        [2.6313, 2.1329, 2.7108, 2.5269],
        [3.1539, 2.7881, 2.9924, 2.7269],
        [2.2746, 2.0668, 2.5790, 2.1520],
        [2.1520, 2.3353, 3.2940, 2.9576],
        [3.4242, 3.6457, 4.7413, 4.2230]])