<a href="https://colab.research.google.com/github/vaibhavlokunde/AI-ML/blob/main/prac2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

**One of the most common errors in deep learning**

In [ ]:
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
# tensor_B=torch.tensor([[7,10],[8,11],[9,12]])
tensor_B=torch.tensor([[7,10,1],[4,5,6]])
torch.matmul(tensor_A,tensor_B)# this will give error as the shape of both is 3x2

tensor([[15, 20, 13],
        [37, 50, 27],
        [59, 80, 41]])

**TRANSPOSE**

In [ ]:
tensor_B.T

tensor([[ 7,  4],
        [10,  5],
        [ 1,  6]])

In [ ]:
tensor_A.shape

torch.Size([3, 2])

In [ ]:
tensor_B.shape


torch.Size([2, 3])

**TENSOR AGGREGATIONS(MIN,MAX,AVG)**

In [ ]:
# Find the min
x=torch.arange(0,100,10)
x
x.min() #OR u can use torch.min(x)

tensor(0)

In [ ]:
#Find the max
x.max()

tensor(90)

In [ ]:
#Find the avg
torch.mean(x)#this throws an error as it only accepts floating point data type

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.mean(x,dtype=torch.float32)

tensor(45.)

In [ ]:
#Find the sum
torch.sum(x) #OR x.sum()

tensor(450)

**FINDING THE POSITION OF MIN AND MAX**

In [ ]:
#for min
x.argmin()

tensor(0)

In [ ]:
#for max
x.argmax()

tensor(9)

**RESHAPING,STACKING,SQUEEZING AND UNSQUEEZING TENSORS**

In [ ]:
#reshaping
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped=x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped=x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
X=torch.arange(1.,11.)
X

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
Xreshape=X.reshape(5,2)
Xreshape

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

**VIEW**

In [ ]:
#View
z=x.view(1,9)  #view is just like reshape but view allows z to copy x jst like it is and changes in x are also changed in z as z is a copy of x
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

**STACKING**

In [ ]:
x_stack=torch.stack([x,x,x,x],dim=0)
x_stack

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stack=torch.stack([x,x,x,x],dim=1)
x_stack

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

**SQUEEZE**

In [ ]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_squeezed=x_reshaped.squeeze()
x_squeezed #this removed one bracket...earlier it had 2 brackets

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#Unsqueezing
x_unsqueezed=x_squeezed.unsqueeze(dim=0) #dim is imp here as without it it will throw error
x_unsqueezed

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

**PERMUTE**

In [ ]:
x_original=torch.rand(size=(224,224,3))
x_original.size()

torch.Size([224, 224, 3])

In [ ]:
torch.permute(x_original,(2,0,1)) #0->2  1->0  2->1

tensor([[[0.0896, 0.8200, 0.8087,  ..., 0.7347, 0.1519, 0.0101],
         [0.3960, 0.0025, 0.9516,  ..., 0.4894, 0.4184, 0.5592],
         [0.1753, 0.0574, 0.8257,  ..., 0.9208, 0.2309, 0.1751],
         ...,
         [0.2058, 0.0722, 0.1654,  ..., 0.1019, 0.6621, 0.9591],
         [0.4280, 0.7872, 0.9646,  ..., 0.7860, 0.4349, 0.2569],
         [0.8808, 0.9705, 0.4697,  ..., 0.6110, 0.2278, 0.6213]],

        [[0.4370, 0.0138, 0.7950,  ..., 0.1532, 0.4198, 0.9903],
         [0.4188, 0.3050, 0.2721,  ..., 0.8494, 0.9201, 0.2694],
         [0.9712, 0.4097, 0.4117,  ..., 0.9669, 0.8444, 0.7575],
         ...,
         [0.5545, 0.6114, 0.0161,  ..., 0.3508, 0.6134, 0.9002],
         [0.5174, 0.2603, 0.4854,  ..., 0.1025, 0.7408, 0.7912],
         [0.5808, 0.9283, 0.0214,  ..., 0.7748, 0.7727, 0.0530]],

        [[0.1403, 0.8641, 0.9433,  ..., 0.4198, 0.9253, 0.2520],
         [0.3761, 0.8346, 0.0300,  ..., 0.7152, 0.8989, 0.2251],
         [0.9860, 0.4010, 0.1195,  ..., 0.3689, 0.9924, 0.

In [ ]:
torch.tensor(7)

tensor(7)

**INDEXING**

In [3]:
x=torch.arange(1,10).reshape(1,3,3);
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
#Indexing in tensor
x[0] #this is in 1D

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
x[0][0] #this is 2D

tensor([1, 2, 3])

In [6]:
x[0][0][0] #this is 3D

tensor(1)

In [9]:
x[0][2][2] #to fetch 9   also x[1][2][2] this is not possible as we set the dimensions as (1,3,3) so 1 is not possible

tensor(9)

In [15]:
x[:,0],x[:,1],x[:,2]

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]), tensor([[7, 8, 9]]))

In [19]:
x[:,:,0],x[:,:,1],x[:,:,2]

(tensor([[1, 4, 7]]), tensor([[2, 5, 8]]), tensor([[3, 6, 9]]))

In [20]:
#get all values from 0th dimension and get 1 index from 1st and 2nd
x[:,1,1]

tensor([5])

**Pytorch tensors & Numpy**


*   Data in NumPy to Pytorch tensor->torch.from_numpy(ndarray)
*   Pytorch to NumPy->torch.Tensor.numpy()



In [22]:
#From numpy to Pytorch tensor
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array) #numpy default is float64 so on conversion it stays the same
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [24]:
array=array+1
array,tensor#no change in tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 1., 1., 1., 1., 1., 1.]))

In [23]:
#from pytorch to numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [25]:
tensor=tensor+1
tensor,numpy_tensor #no change in numpy_tensor


(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))